# Generated by Django 5.2.7 on 2025-10-14 09:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0001_initial"),
        ("requests", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="borrowrequest",
            options={"ordering": ["-request_date"]},
        ),
        migrations.RenameField(
            model_name="borrowrequest",
            old_name="date_returned",
            new_name="return_date",
        ),
        migrations.RemoveField(
            model_name="borrowrequest",
            name="date_borrowed",
        ),
        migrations.RemoveField(
            model_name="borrowrequest",
            name="student",
        ),
        migrations.AddField(
            model_name="borrowrequest",
            name="request_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="borrowrequest",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="borrow_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="borrowrequest",
            name="equipment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="borrow_requests",
                to="equipment.equipment",
            ),
        ),
        migrations.AlterField(
            model_name="borrowrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("declined", "Declined"),
                    ("returned", "Returned"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
